### ISSUE TITLE
Start MicMute.exe on Windows 10 Startup

### ISSUE THREAD

**Issue by alexcarinci** [Anc813/MicMute#10]
I have added a shortcut to the Windows 10 startup folder (shell:startup), however, the app will not start with Windows. Is there anyway to accomplish this? I have also toggled the switch in Startup Apps but it is not working.

**Comment by Anc813** [comment]
@alexcarinci 
1. Ensure shortcut exists in this folder (paste this in windows explorer)
"%AppData%\Microsoft\Windows\Start Menu\Programs\Startup"

2. Ensure you can run the program with double click on shortcut in this folder.

**Comment by alexcarinci** [comment]
Yes the shortcut is there and it opens the app with a double click. I have also set it to run as Administrator, but it won't start with Windows :(

**Comment by roughnecks** [comment]
> I have also set it to run as Administrator, but it won't start with Windows :(

That's the problem, autostart won't work with Admin rights, you'll have to use a Scheduled Task for that.

**Comment by Anc813** [comment]
@alexcarinci check that MicMute exists in windows 10 "task manager" at "startup" tab and it enabled

**Comment by alexcarinci** [comment]
> > I have also set it to run as Administrator, but it won't start with Windows :(
> 
> That's the problem, autostart won't work with Admin rights, you'll have to use a Scheduled Task for that.

This was the issue!! Thanks so much @roughnecks. I unchecked all instances of Run as Administrator and it's working as intended now! Awesome program @Anc813!

**Comment by innesst** [comment]
Go to Settings -> Apps -> Startup and toggle the switch
