### ISSUE TITLE
Manually select MIC

### ISSUE THREAD

**Issue by roughnecks** [Anc813/MicMute#11]
Hello,

would it be possible to implement a function that lets user select which Microphone device they want to mute, instead of auto-selecting default in Windows?

Thanks

**Comment by Anc813** [comment]
@roughnecks 
1. How should it work when selected mic have been disconnected or unavailiable?
2. I need at least two mics to test this feature. Currently I don't have two.

**Comment by roughnecks** [comment]
1. It could set the other one as default. But isn't this the same with 1 Mic, if user disconnects it?
2. You could install VoiceMeeter Banana and you'll have a couple more input devices to work with (if you want, that is).

**Comment by Anc813** [comment]
@roughnecks 
So, if selected mic is unavailable - then show unavailable icon until it will be connected again or another mic will be selected.

Could You test this new version please?

[MicMute.zip](https://github.com/Anc813/MicMute/files/6424130/MicMute.zip)

**Comment by roughnecks** [comment]
> @roughnecks
> So, if selected mic is unavailable - then show unavailable icon until it will be connected again or another mic will be selected.

I cannot test this, but I think that's just fine..
 
> Could You test this new version please?
> 
> [MicMute.zip](https://github.com/Anc813/MicMute/files/6424130/MicMute.zip)

Working wonders! Thanks
