### ISSUE TITLE
Audio Output Device in Windows

### ISSUE THREAD

**Issue by roughnecks** [Anc813/MicMute#16]
Hey,

I was wondering why this isn't working and if you can fix it..

https://i.imgur.com/bFqcnqB.jpeg

If I select any other output device which isn't default ("Predefinito" in Italian), MicMute doesn't acknowledge it and keeps playing the "on" and "off" sounds on the default device.

Thanks

**Comment by Anc813** [comment]
@roughnecks it uses SoundPlayer Class to play sound https://github.com/Anc813/MicMute/blob/master/MainForm.cs#L152
https://docs.microsoft.com/en-us/dotnet/api/system.media.soundplayer

Unfortunately, there is no option to specify output device.

**Comment by roughnecks** [comment]
I see. Thanks anyway.
