### ISSUE TITLE
Sound feature

### ISSUE THREAD

**Issue by Chipsnet** [Anc813/MicMute#2]
I love this software, but there is one problem.
It doesn't make a sound.
I used it as an alternative to Discord's mute button. As a result, all software mutes are consistent with this software and it worked for me.
However, since there is no sound, you have to check the task tray to see if it has been muted.
If there is sound, you don't have to check the task tray every time.
Can you implement this feature, if you would?

**Comment by Anc813** [comment]
@Chipsnet 
Feature implemented.
But You need to create sound files by youself
Create "on.wav" sound file with unmute sound (when mic is being turned on) and place it in same folder where "MicMute.exe" is located.
Create "off.wav" sound file with unmute sound (when mic is being turned off) and place it in same folder where "MicMute.exe" is located.
These sounds will be also played when the program starts.

You should find sounds somewhere (for example discord sounds in mp3 files can be found [here](https://twitter.com/discord/status/763869796236525568/))
And then convert them to WAV format using some online converter (for example https://online-audio-converter.com/)

If You like discord sounds - just download and unpack [this zip archive](https://github.com/Anc813/MicMute/files/4977695/MicMute.zip)

**Comment by Chipsnet** [comment]
omg it's completely works for me!

**Comment by phuein** [comment]
The default volume on those is a bit loud for me, so here's a "low" version at -35db edited with Audacity: https://drive.google.com/file/d/1uh1eFB8Q87nM3HGoyKNHzi51MUqTXajp/view?usp=sharing
