### ISSUE TITLE
Long device names are unhandled

### ISSUE THREAD

**Issue by bogdan-calapod** [Anc813/MicMute#25]
I get this error when starting the program:

![image](https://user-images.githubusercontent.com/5462727/138734760-f5b4d5cf-7fe9-4b21-afc8-abb73d5c879f.png)

Seems to be a small issue where the string length is longer than expected

**Comment by Anc813** [comment]
@bogdan-calapod  can You try download now?

**Comment by bogdan-calapod** [comment]
![image](https://user-images.githubusercontent.com/5462727/140729768-e3db39bd-1ebd-496a-8c8e-034fb0b38b98.png)

I just downloaded the zip you sent, no security error now but this shows up instead 😕

**Comment by Anc813** [comment]
@bogdan-calapod  i can't reproduce this issue, I don't have device with long names
I fixed it in some places I suggested.
But there is more, and I can't find them without debugger

**Comment by dwettstein** [comment]
![image](https://user-images.githubusercontent.com/412133/147925279-6b2e029f-e1b2-4548-808c-3c7f6e22d63d.png)

I have the same issue on my device and will try to fix it and submit a PR.
