### ISSUE TITLE
Does nothing?

### ISSUE THREAD

**Issue by mblais** [Anc813/MicMute#4]
When I run the MicMute.exe, nothing happens.... I see it running in Task Manager, but it opens no windows, no icon in the task bar.

What am I missing?

Windows 10 x64

**Comment by Anc813** [comment]
There should be icon in taskbar.
Maybe You have some kind of mic, that this application can not detect.

**Comment by dwettstein** [comment]
This issue could be closed. 😇

**Comment by mblais** [comment]
Not sure how/why, but this issue did resolve itself.
