### ISSUE TITLE
Play a short sound when the microphone is muted or activated (two different sounds)

### ISSUE THREAD

**Issue by matomosh** [Anc813/MicMute#43]
I found this utility very convenient for managing the microphone directly from the play/pause button of my Bluetooth earphones connected to the PC while I am on a call on MS Teams. And it would be even more useful if it also had a short sound feedback to know when the microphone is activated or muted when you are away from the screen. Good job

**Comment by dev1tet** [comment]
@matomosh  please see https://github.com/Anc813/MicMute/issues/2
This is already implemented

> But You need to create sound files by youself
> Create "on.wav" sound file with unmute sound (when mic is being turned on) and place it in same folder where "MicMute.exe" is located.
> Create "off.wav" sound file with unmute sound (when mic is being turned off) and place it in same folder where "MicMute.exe" is located.
> These sounds will be also played when the program starts.
> 
> You should find sounds somewhere (for example discord sounds in mp3 files can be found [here](https://twitter.com/discord/status/763869796236525568/))
> And then convert them to WAV format using some online converter (for example https://online-audio-converter.com/)
> 
> If You like discord sounds - just download and unpack [this zip archive](https://github.com/Anc813/MicMute/files/4977695/MicMute.zip)

**Comment by Anc813** [comment]
@matomosh please see #2
This is already implemented

    But You need to create sound files by youself
    Create "on.wav" sound file with unmute sound (when mic is being turned on) and place it in same folder where "MicMute.exe" is located.
    Create "off.wav" sound file with unmute sound (when mic is being turned off) and place it in same folder where "MicMute.exe" is located.
    These sounds will be also played when the program starts.

    You should find sounds somewhere (for example discord sounds in mp3 files can be found here)
    And then convert them to WAV format using some online converter (for example https://online-audio-converter.com/)

    If You like discord sounds - just download and unpack this zip archive
